### ISSUE TITLE
Fatal exception on changing nicks

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#102]
```
2016-07-18 00:05:11 ERROR:BridgedClient <DeeEff[m]@irc.freenode.net#763jhgudigsgo> (@ThatGeoGuy:matrix.org) Timed out trying to change nick to ThatGeoGuy
2016-07-18 00:05:11 ERROR:main FATAL EXCEPTION
2016-07-18 00:05:11 ERROR:main TypeError: Cannot read property 'removeListener' of undefined
    at null._onTimeout (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/BridgedClient.js:205:30)
    at Timer.listOnTimeout (timers.js:92:15)
2016-07-18 00:05:11 ERROR:main Terminating (exitcode=1)
```

**Comment by Kegsay** [comment]
Caused by: Race condition.

Reproduction steps
 - Connect to IRC.
 - Send `!nick Whatever`
 - Connection is knifed after `NICK` is sent but before the reply comes back.
 - Nick request times out.
 - `this.unsafeClient` is nullified.
 - `this.unsafeClient` is accessed at `:205`.
