### ISSUE TITLE
Failure on startup

### ISSUE THREAD

**Issue by voice06** [matrix-org/matrix-appservice-irc#1051]
I am trying to setup a new irc bridge and while it starts and connects to the irc side it seems like a thread or something else is failing. The end result is the IRC side stays up and seemingly responsive as it doesn't ping out and the irc bot responds to PMs but it looks like maybe the Matrix side is what crashed?

```
2020-05-12 03:26:00 INFO:BridgedClient <MatrixBot@sonikku.afternet.org#j602f9lqtns00> Connecting to IRC server sonikku.afternet.org as MatrixBot (user=matrixirc)
2020-05-12 03:26:01 DEBUG:client-connection Received ping from 455966613 directed at MatrixBot
FATAL EXCEPTION
TypeError: Cannot read property 'length' of undefined
    at Client._splitMessage (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1147:58)
    at Client._speak (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1161:30)
    at Client.notice (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1142:17)
    at Client.ctcp (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1265:55)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/lib/irc/ConnectionInstance.js:276:25)
    at Client.emit (events.js:310:20)
    at Client.EventEmitter.emit (domain.js:482:12)
    at Client._handleCTCP (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1257:14)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:612:26)
    at Client.emit (events.js:322:22)
    at Client.EventEmitter.emit (domain.js:482:12)
    at iterator (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:934:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:929:15)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
2020-05-12 03:26:06 ERROR:main FATAL EXCEPTION
2020-05-12 03:26:06 ERROR:main TypeError: Cannot read property 'length' of undefined
    at Client._splitMessage (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1147:58)
    at Client._speak (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1161:30)
    at Client.notice (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1142:17)
    at Client.ctcp (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1265:55)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/lib/irc/ConnectionInstance.js:276:25)
    at Client.emit (events.js:310:20)
    at Client.EventEmitter.emit (domain.js:482:12)
    at Client._handleCTCP (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:1257:14)
    at Client.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:612:26)
    at Client.emit (events.js:322:22)
    at Client.EventEmitter.emit (domain.js:482:12)
    at iterator (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:934:26)
    at Array.forEach (<anonymous>)
    at TLSSocket.<anonymous> (/home/afternet/matrix-appservice-irc-0.17.1/node_modules/irc/lib/irc.js:929:15)
    at TLSSocket.emit (events.js:310:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
2020-05-12 03:26:06 ERROR:main Terminating (exitcode=1)
2020-05-12 03:26:06 INFO:PgDatastore Fetching all channels for sonikku.afternet.org
2020-05-12 03:26:06 INFO:IrcBridge Startup complete.
```

Not sure of exact steps to reproduce other than config and start.

Version: 0.17.1
Ircd: NefariousIRCu u2.10.12.14+Nefarious(2.0.0)+[2.0-228-ged12d64]

I do have 0.17.0 running on another network using the same ircd (u2.10.12.14+Nefarious(2.0.0)+[2.0-223-ged6b679]) which is showing no issues.

**Comment by voice06** [comment]
Heres telnet run to show what the connection process is looking like if it helps:

Connected to sonikku.afternet.org.
Escape character is '^]'.
NOTICE * :*** Looking up your hostname
NOTICE * :*** Couldn't look up your hostname
USER voicetest voicetest * * :voicetest
NICK voicetest
PING :1931052582
PONG :1931052582
NOTICE * :*** Checking your client version (sorry..)
:Sonikku.AfterNET.Org PRIVMSG voicetest :VERSION
:Sonikku.AfterNET.Org 001 voicetest :Welcome to the AfterNET IRC Network, voicetest
:Sonikku.AfterNET.Org 002 voicetest :Your host is Sonikku.AfterNET.Org, running version u2.10.12.14+Nefarious(2.0.0)
:Sonikku.AfterNET.Org 003 voicetest :This server was created Sat 11 Apr UTC at 2020 04:43:15 PM
:Sonikku.AfterNET.Org 004 voicetest Sonikku.AfterNET.Org u2.10.12.14+Nefarious(2.0.0) adgiknoqswxzBDHLNORWX abCcDdhikLlMmNnOopQRrSsTtvZz bhkLlov
:Sonikku.AfterNET.Org 005 voicetest WHOX WALLCHOPS WALLHOPS WALLVOICES USERIP CPRIVMSG CNOTICE NAMESX UHNAMES SILENCE=25 WATCH=128 MODES=6 MAXCHANNELS=50 :are supported by this server
:Sonikku.AfterNET.Org 005 voicetest MAXBANS=50 NICKLEN=30 MAXNICKLEN=30 TOPICLEN=250 AWAYLEN=250 KICKLEN=250 CHANNELLEN=200 MAXCHANNELLEN=200 CHANTYPES=# PREFIX=(ohv)@%+ STATUSMSG=@%+ CHANMODES=be,k,Ll,aCcDdiMmNnOpQRrSsTtZz CASEMAPPING=rfc1459 :are supported by this server
:Sonikku.AfterNET.Org 005 voicetest NETWORK=AfterNET MAXLIST=b:50,e:45 ELIST=CT EXCEPTS=e MAXEXCEPTS=45 EXTBANS=~,acjnqrmM :are supported by this server
:Sonikku.AfterNET.Org 251 voicetest :There are 358 users and 194 invisible on 13 servers
:Sonikku.AfterNET.Org 252 voicetest 20 :operator(s) online
:Sonikku.AfterNET.Org 254 voicetest 255 :channels formed
:Sonikku.AfterNET.Org 255 voicetest :I have 5 clients and 1 servers
:Sonikku.AfterNET.Org 265 voicetest :Current local users: 5 Max: 17
:Sonikku.AfterNET.Org 266 voicetest :Current global users: 552 Max: 591
:Sonikku.AfterNET.Org NOTICE voicetest :Highest connection count: 18 (17 clients)
:Sonikku.AfterNET.Org 375 voicetest :- Sonikku.AfterNET.Org Message of the Day - 
:Sonikku.AfterNET.Org 372 voicetest :See http://www.afternet.org for information about this network.
:Sonikku.AfterNET.Org 372 voicetest :Type /MOTD to read the AUP before continuing using this service.
:Sonikku.AfterNET.Org 372 voicetest :The message of the day was last changed: 2020-4-8 22:8
:Sonikku.AfterNET.Org 376 voicetest :End of /MOTD command.
:Sonikku.AfterNET.Org NOTICE voicetest :on 1 ca 2(6) ft 10(10) tr
:Sonikku.AfterNET.Org 396 voicetest DCA8FD:7F8813:60B91F:30675A:IP :is now your hidden host
:voicetest!voicetest@DCA8FD:7F8813:60B91F:30675A:IP MODE voicetest +x
QUIT :Quit
Connection closed by foreign host.

**Comment by Half-Shot** [comment]
The ircd is sending `:Sonikku.AfterNET.Org PRIVMSG voicetest :VERSION` which doesn't give a viable response nick (as 'Sonikku.AfterNET.Org' isn't a nick as far as node-irc) is concerned. I can at least fix the bridge to ignore requests without a valid sender, however.
