### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by meatballs** [matrix-org/matrix-appservice-irc#1061]
When I clone this repo and attempt to run the tests, I get:

```
> matrix-appservice-irc@0.17.1 test /root/matrix-appservice-irc
> BLUEBIRD_DEBUG=1 node --max_old_space_size=3072 node_modules/jasmine/bin/jasmine.js --stop-on-failure=true

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../../lib/promiseutil'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/matrix-appservice-irc/spec/util/irc-client-mock.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/matrix-appservice-irc/spec/util/test.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/matrix-appservice-irc/spec/util/env-bundle.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! Test failed.  See above for more details.
```

**Comment by Half-Shot** [comment]
Hey there, I'm not seeing these failures :(.

For reference, I ran:
```sh
git clone git@github.com:matrix-org/matrix-appservice-irc.git
cd matrix-appservice-irc
npm i
npm test
> ....
> 201 specs, 0 failures
> Finished in 6.491 seconds
node --version
```

**Comment by neilmckillop** [comment]
I'm having the same issue.  Line 3 in spec/unit/promiseutil.spec.js seems to be the culprit:
`const promiseutil = require("../../lib/promiseutil");`
Not sure where that is meant to be.

**Comment by Half-Shot** [comment]
Okay, builds should be triggered by calling `npm install`, but have you tried running `npm run build` before running the tests?

**Comment by neilmckillop** [comment]
> 
> 
> Okay, builds should be triggered by calling `npm install`, but have you tried running `npm run build` before running the tests?

Thanks Half-Shot, this seems to have fixed it.  It was failing next with this error:
```
../matrix-appservice-irc/node_modules/matrix-lastactive/lib/lib.js:78
        catch {
              ^
SyntaxError: Unexpected token {
```
But commenting out that try/catch block seemed to let me finish the test:
```
201 specs, 0 failures
Finished in 12.355 seconds
```
Thanks for your help!

**Comment by Half-Shot** [comment]
I've sadly not been able to repro this anywhere. As of today, we require NodeJS 12.X anyway on `develop`.
