### ISSUE TITLE
Uncaught promise: "Failed to join room"

### ISSUE THREAD

**Issue by jaller94** [matrix-org/matrix-appservice-irc#1067]
One of our IRC bridges has sometimes issues joining the puppet of an IRC user into a Matrix room.

Tested versions:
* matrix-appservice-irc-0.17.0-rc4

When this happens the homeserver responds 404
`{"errcode":"M_UNKNOWN","error":"No known servers"}`

to which the following line throws an uncaught promise:

```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Failed to join room
    at /opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-appservice-bridge/lib/components/intent.js:649:49
    at tryCatcher (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/promise.js:695:18)
    at _drainQueueStep (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/matrix-appservice-irc-0.17.0-rc4/node_modules/matrix-js-sdk/node_modules/bluebird/js/release/async.js:147:5)
```

**Comment by Half-Shot** [comment]
Suspect that's a bug in `matrix-appservice-bridge`
