### ISSUE TITLE
Connection with `?sslmode=require` throws stack trace

### ISSUE THREAD

**Issue by Routhinator** [matrix-org/matrix-appservice-irc#1083]
Hi folks, how do I get this bridge to use SSL on the database connection? I've added the `?sslmode=require` on the connection string and I just get a stack trace:
 ```
 2020-07-17 03:37:09 INFO:PgDatastore Starting postgres database engine
 2020-07-17 03:37:09 ERROR:PgDatastore Failed to get schema version: error: SSL required
     at Connection.parseE (/app/node_modules/pg/lib/connection.js:581:48)
     at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:380:19)
     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:116:22)
     at Socket.emit (events.js:315:20)
     at Socket.EventEmitter.emit (domain.js:482:12)
     at addChunk (_stream_readable.js:295:12)
     at readableAddChunk (_stream_readable.js:271:9)
     at Socket.Readable.push (_stream_readable.js:212:10)
     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
   length: 33,
   severity: 'ERROR',
   code: '08P01',
   detail: undefined,
   hint: undefined,
   position: undefined,
   internalPosition: undefined,
   internalQuery: undefined,
   where: undefined,
   schema: undefined,
   table: undefined,
   column: undefined,
   dataType: undefined,
   constraint: undefined,
   file: undefined,
   line: undefined,
   routine: undefined
 }
 2020-07-17 03:37:09 ERROR:CLI Failed to run bridge.
 ```

Anyone have any ideas on this? I'm using a Digital Ocean managed db for synapse, SSL is required. But the documentation mentions nothing about ssl, and the proper connection string causes the bridge to puke.

**Comment by Routhinator** [comment]
I'm quite convinced this is a bug now.

**Comment by Half-Shot** [comment]
It's a misconfiguration, it should be `?ssl=require`

**Comment by Routhinator** [comment]
That's a different flag @Half-Shot - and the `ssl` flag takes `true` 

I finally got this working with a Digital Ocean Managed DB and the following needed to be done:

Add `?ssl=true&sslmode=require` to the connection string and pass the `NODE_TLS_REJECT_UNAUTHORIZED = 0` environment variable to disable certificate verification as DO uses a self signed cert.

**Comment by lhorace** [comment]
If you happened to have the CA cert, this works for me: `postgres://username:password@host:port/ircbridge?ssl=true&sslmode=verify-full&sslrootcert=/path/to/ca.pem`
