### ISSUE TITLE
metrics worker can choke on writes

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1108]
```
Aug 12 18:21:23 lethe freenodeirc[30619]: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Aug 12 18:21:23 lethe freenodeirc[30619]:     at write_ (_http_outgoing.js:629:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at ServerResponse.write (_http_outgoing.js:621:15)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.<anonymous> (/opt/freenodeirc/matrix-appservice-irc-0.20.0-rc1/lib/workers/MetricsWorker.js:49:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at Object.onceWrapper (events.js:422:26)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.emit (events.js:327:22)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.onmessage (internal/worker/io.js:78:8)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
Aug 12 18:21:23 lethe freenodeirc[30619]: FATAL EXCEPTION
Aug 12 18:21:23 lethe freenodeirc[30619]: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Aug 12 18:21:23 lethe freenodeirc[30619]:     at write_ (_http_outgoing.js:629:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at ServerResponse.write (_http_outgoing.js:621:15)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.<anonymous> (/opt/freenodeirc/matrix-appservice-irc-0.20.0-rc1/lib/workers/MetricsWorker.js:49:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at Object.onceWrapper (events.js:422:26)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.emit (events.js:327:22)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.onmessage (internal/worker/io.js:78:8)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
Aug 12 18:21:23 lethe freenodeirc[30619]: 2020-08-12 18:21:22 ERROR:main FATAL EXCEPTION
Aug 12 18:21:23 lethe freenodeirc[30619]: 2020-08-12 18:21:22 ERROR:main Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Aug 12 18:21:23 lethe freenodeirc[30619]:     at write_ (_http_outgoing.js:629:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at ServerResponse.write (_http_outgoing.js:621:15)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.<anonymous> (/opt/freenodeirc/matrix-appservice-irc-0.20.0-rc1/lib/workers/MetricsWorker.js:49:17)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at Object.onceWrapper (events.js:422:26)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.emit (events.js:327:22)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.onmessage (internal/worker/io.js:78:8)
Aug 12 18:21:23 lethe freenodeirc[30619]:     at MessagePort.exports.emitMessage (internal/per_context/messageport.js:11:10)
Aug 12 18:21:23 lethe freenodeirc[30619]: 2020-08-12 18:21:22 ERROR:main Terminating (exitcode=1)
```

**Comment by Half-Shot** [comment]
Fixed by #1109
