### ISSUE TITLE
Error in killUser debug endpoint: Cannot read property 'getBridgedClientsForUserId' of undefined

### ISSUE THREAD

**Issue by silkeh** [matrix-org/matrix-appservice-irc#1199]
**Describe the bug**
The `killUser` debug endpoint gives me the following response:
```
TypeError: Cannot read property 'getBridgedClientsForUserId' of undefined
```

The logs show:

```
2020-12-02 12:05:41 ERROR:DebugApi TypeError: Cannot read property 'getBridgedClientsForUserId' of undefined
    at DebugApi.killUser (/usr/local/share/.config/yarn/global/node_modules/matrix-appservice-irc/lib/DebugApi.js:220:35)
    at IncomingMessage.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/matrix-appservice-irc/lib/DebugApi.js:157:36)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**To Reproduce**
Steps to reproduce the behavior (with HTTPie):

```
$ http :11101/killUser access_token==$token user_id=<redacted> reason=deprecation deactivate:=false
HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Type: text/plain
Date: Wed, 02 Dec 2020 11:05:33 GMT
Keep-Alive: timeout=5
Transfer-Encoding: chunked

TypeError: Cannot read property 'getBridgedClientsForUserId' of undefined
```

**Expected behavior**
A successfull response.

**Server:**
 - OS: Debian 10.6
- NodeJS version: v12.20.0
 - Bridge Version: 0.23.0

**Comment by jaller94** [comment]
Line in question:
https://github.com/matrix-org/matrix-appservice-irc/blob/4bce52a340f33313857c8e3e6ab16defaae94ea9/src/DebugApi.ts#L242

`this.pool` seems to have a chance to be `undefined`.

**Comment by jaller94** [comment]
Found the issue: `IrcBridge.run()` is an async function. It first creates DebugApi and then the ClientPool but uses an await in between. While the ClientPool hasn't been created, the processing in DebugApi will fail.

https://github.com/matrix-org/matrix-appservice-irc/blob/4bce52a340f33313857c8e3e6ab16defaae94ea9/src/bridge/IrcBridge.ts#L534-L569
