### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by carbolymer** [matrix-org/matrix-appservice-irc#1201]
**Describe the bug**
During connection attempt `TypeError: Converting circular structure to JSON` is logged repeatably in the log files.

**To Reproduce**
1. just add `open.ircnet.com` server in the servers configuration. Sample configuration:
```
servers:
        open.ircnet.com:
            allowExpiredCerts: true
            botConfig:
                enabled: false
                joinChannelsIfNoUsers: true
                nick: MatrixBot
            dynamicChannels:
                aliasTemplate: '#ircnet_$CHANNEL'
                createAlias: true
                enabled: true
                federate: true
                groupId: +irc:localhost
                joinRule: public
                published: true
            ircClients:
                allowNickChanges: true
                concurrentReconnectLimit: 50
                idleTimeout: 10800
                lineLimit: 6
                maxClients: 300
                nickTemplate: $DISPLAY[m]
                reconnectIntervalMs: 5000
            matrixClients:
                displayName: $NICK (IRC)
                joinAttempts: -1
                userTemplate: '@$SERVER_$NICK'
            membershipLists:
                enabled: true
                floodDelayMs: 10000
                global:
                    ircToMatrix:
                        incremental: true
                        initial: true
                    matrixToIrc:
                        incremental: true
                        initial: true
            name: IRCNet
            port: 6697
            privateMessages:
                enabled: true
                federate: true
            sasl: false
            sendConnectionMessages: true
            ssl: true
```

**Expected behavior**
No error messages

**Log**
```
Dec 07 21:27:44 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:44 INFO:client-connection disconnect()ing MatrixBot@open.ircnet.com - timeout
Dec 07 21:27:44 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:44 ERROR:client-connection ConnectionInstance.connect failed after 22 attempts (timeout)
Dec 07 21:27:44 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:44 INFO:client-connection Retrying connection for MatrixBot on open.ircnet.com in 576.9231054481259ms (attempts 22)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: FATAL EXCEPTION
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: TypeError: Converting circular structure to JSON
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     --> starting at object with constructor 'Object'
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     --- property 'issuerCertificate' closes the circle
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at JSON.stringify (<anonymous>)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.<anonymous> (/app/lib/irc/ConnectionInstance.js:192:89)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.emit (events.js:310:20)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.EventEmitter.emit (domain.js:482:12)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.<anonymous> (/app/node_modules/irc/lib/irc.js:958:14)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.emit (events.js:310:20)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 ERROR:main FATAL EXCEPTION
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 ERROR:main TypeError: Converting circular structure to JSON
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     --> starting at object with constructor 'Object'
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     --- property 'issuerCertificate' closes the circle
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at JSON.stringify (<anonymous>)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.<anonymous> (/app/lib/irc/ConnectionInstance.js:192:89)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.emit (events.js:310:20)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at Client.EventEmitter.emit (domain.js:482:12)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.<anonymous> (/app/node_modules/irc/lib/irc.js:958:14)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.emit (events.js:310:20)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 ERROR:main Terminating (exitcode=1)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 ERROR:client-connection Server: open.ircnet.com (MatrixBot) Connection Aborted
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 INFO:client-connection disconnect()ing MatrixBot@open.ircnet.com - net_error
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 ERROR:client-connection ConnectionInstance.connect failed after 23 attempts (net_error)
Dec 07 21:27:45 matrix matrix-appservice-irc[18204]: 2020-12-07 21:27:45 INFO:client-connection Retrying connection for MatrixBot on open.ircnet.com in 16210.865762854335ms (attempts 23)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: FATAL EXCEPTION
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 ERROR:main FATAL EXCEPTION
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 ERROR:main TypeError: Converting circular structure to JSON
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     --> starting at object with constructor 'Object'
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     --- property 'issuerCertificate' closes the circle
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at JSON.stringify (<anonymous>)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at Client.<anonymous> (/app/lib/irc/ConnectionInstance.js:192:89)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at Client.emit (events.js:310:20)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at Client.EventEmitter.emit (domain.js:482:12)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at TLSSocket.<anonymous> (/app/node_modules/irc/lib/irc.js:958:14)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at TLSSocket.emit (events.js:310:20)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at emitErrorNT (internal/streams/destroy.js:92:8)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 ERROR:main Terminating (exitcode=1)
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 ERROR:client-connection Server: open.ircnet.com (MatrixBot) Connection Aborted
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 INFO:client-connection disconnect()ing MatrixBot@open.ircnet.com - net_error
Dec 07 21:28:01 matrix matrix-appservice-irc[18204]: 2020-12-07 21:28:01 ERROR:client-connection ConnectionInstance.connect failed after 24 attempts (net_error
```

**Comment by Half-Shot** [comment]
Does this happen if you try with another network? I strongly suspect there is a problem with this IRCd setup?

**Comment by carbolymer** [comment]
> Does this happen if you try with another network? I strongly suspect there is a problem with this IRCd setup?

No, it seems to be specific open.ircnet.com & SSL combination. snoonet & freenode works with SSL. Ircnet without SSL works too, obviously.

**Comment by Half-Shot** [comment]
Having had a go just trying to connect with an IRC client, it appears that I can't even get a connection over 6697 :(. I think the error you got is misleading but there is certainly a problem with the IRCd here.

**Comment by Half-Shot** [comment]
I'm going to close this and say that it's probably a symptom of a broken IRCd.
