### ISSUE TITLE
Failed to find libnode64.so on Debian Buster

### ISSUE THREAD

**Issue by KlaasT** [matrix-org/matrix-appservice-irc#1218]
Today I tried to move the matrix-appservice-irc to a new Debian 10 machine with nodejs 12.x installed. When I start the app a connection is being established to the Matrix homeserver and after some time the app will try to connect to IRC.

While connecting to IRC the following happens:

> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]: FATAL EXCEPTION
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]: Error: libnode.so.64: cannot open shared object file: No such file or directory
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Module.load (internal/modules/cjs/loader.js:863:32)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Module.require (internal/modules/cjs/loader.js:887:19)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at require (internal/modules/cjs/helpers.js:74:18)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Object.<anonymous> (/usr/local/lib/node_modules/matrix-appservice-irc/node_modules/iconv/lib/iconv.js:27:14)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Module._compile (internal/modules/cjs/loader.js:999:30)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Module.load (internal/modules/cjs/loader.js:863:32)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at Module.require (internal/modules/cjs/loader.js:887:19)
> Jan 11 13:13:03 Matrix matrix-appservice-irc[22310]:     at require (internal/modules/cjs/helpers.js:74:18)

As I don't have much experience with nodejs I thought I could just install the "libnode64" package on Debian. However this package conflicts with nodejs 12 and is not installable.

Is there maybe something missing in the install instructions or something which needs to be done especially for Debian based systems?

Thanks for any help.

**Comment by Half-Shot** [comment]
>Is there maybe something missing in the install instructions or something which needs to be done especially for Debian based systems?

This should work on stock Node.JS 12 and up systems, no special requirements. This sounds like you have a faulty nodejs environment. One thing you can try is https://github.com/nvm-sh/nvm to install different versions locally for the application and see if those work better for you?

**Comment by jaller94** [comment]
Closing stale issue.
The bridge runs well with all current versions of NodeJS.
