### ISSUE TITLE
Event not found / Server not known

### ISSUE THREAD

**Issue by cremesk** [matrix-org/matrix-appservice-irc#1222]
hello, for some time now I've been getting the following errors:

```
ERROR:IrcBridge Homeserver cannot reach the bridge. You probably need to adjust your configuration. Timeout waiting for ping event
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!CQTWkbjTNVeXvCSwgP%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23twtxt (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!VEAxMzWIUMXBPClYHX%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23projects (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!wLcaYYSPIiDNdDPniR%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23envs (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!HmWWoQyDkBLxeTgdZQ%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23envs_lounge (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!UCdDvPPYEQfWIEAWRO%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23envs_german (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!CnUZwIaxkfCjPzRirV%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23envs_news (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!evSgAbCmYveqfawWOs%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23tildeverse (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ERROR:IrcBridge [-] GET https://matrix.envs.net/_matrix/client/r0/rooms/!UBEkMQdtHOOPSgbtxO%3Aenvs.net/state/uk.half-shot.bridge/org.matrix.appservice-irc%3A%2F%2Firc%2FTildeChat%2F%23envs_dev (AS) HTTP 404 Error: "{\"errcode\":\"M_NOT_FOUND\",\"error\":\"Event not found.\"}"
ERROR:main Error: Server not known
    at BridgeStateSyncer.createBridgeInfoContent (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:81:19)
    at BridgeStateSyncer.syncRoom (/opt/matrix-appservice-irc/lib/bridge/BridgeStateSyncer.js:54:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I just don't know why .. the bridge worked for a year without any problems.
the bridge only works from irc to matrix. but not from matrix to irc.
Any Idea what i can check?

matrix-appservice-irc version is: 0.23.0

the homeserver know the appservice-registration-irc.yaml
```
# A list of application service config files to use
#
app_service_config_files:
  - "/opt/matrix-appservice-irc/appservice-registration-irc.yaml"
 ```

**Comment by Half-Shot** [comment]
This seems to imply that your matrix server can't talk to your IRC bridge. Can you look at your synapse logs and check if Synapse is able to push appservice transactions to it?

(Server not known errors are annoying, but I don't think they are the cause)

**Comment by cremesk** [comment]
I've looked and I've been seeing something like this for some time:

```
$ tail -f /var/log/daemon.log | grep "appservice"                                                                                                                                                                                             
Jan 23 19:36:58 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:36:58,805 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45188 - [TXN OPERROR] {set_type_stream_id_for_appservice-17c85} could not serialize access due to concurrent update
Jan 23 19:36:58 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:00 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:00,379 - synapse.metrics - 576 - INFO - None - Collecting gc 1                                                                                                       
Jan 23 19:37:02 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:02,200 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45209 - [TXN OPERROR] {set_type_stream_id_for_appservice-17cb7} could not serialize access due to concurrent update
Jan 23 19:37:02 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:03,452 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45219 - [TXN OPERROR] {set_type_stream_id_for_appservice-17cd0} could not serialize access due to concurrent update
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:03,452 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45220 - [TXN OPERROR] {set_type_stream_id_for_appservice-17ccf} could not serialize access due to concurrent update
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:03,453 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45220 - [TXN OPERROR] {set_type_stream_id_for_appservice-17ccf} could not serialize access due to concurrent update
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]:  1/5
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:03,781 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45222 - [TXN OPERROR] {set_type_stream_id_for_appservice-17cde} could not serialize access due to concurrent update
Jan 23 19:37:03 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:07 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:07,855 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45243 - [TXN OPERROR] {set_type_stream_id_for_appservice-17d09} could not serialize access due to concurrent update
Jan 23 19:37:07 matrix matrix-synapse-appservice[9248]:  0/5
Jan 23 19:37:09 matrix matrix-synapse-appservice[9248]: 2021-01-23 19:37:09,316 - synapse.storage.txn - 517 - WARNING - notify_interested_services_ephemeral-45254 - [TXN OPERROR] {set_type_stream_id_for_appservice-17d22} could not serialize access due to concurrent update
Jan 23 19:37:09 matrix matrix-synapse-appservice[9248]:  0/5
```

is it related?

**Comment by Half-Shot** [comment]
That's mostly fine, just a bit spammy. I'd expect something like "Starting recoverer for foobar",  "push_bulk to %s received" or "push_bulk to %s threw exception"

**Comment by cremesk** [comment]
hmm unfortunately I don't see anything of that here.

**Comment by cremesk** [comment]
I think i found the issue..
https://github.com/matrix-org/synapse/issues/1834

`update appservice_stream_position set stream_ordering = (select max(stream_ordering) from events);`

helps here to reactivate the bridge.
just what happened there?
