### ISSUE TITLE
Config reloader throws if optional keys are not defined

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-appservice-irc#1340]
```
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]: 2021-05-26 21:31:26 INFO:IrcBridge Bridge config was reloaded, applying changes
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]: 2021-05-26 21:31:26 ERROR:main TypeError: Cannot read property 'maxHttpSockets' of undefined
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]:     at IrcBridge.onConfigChanged (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/lib/bridge/IrcBridge.js:183:32)
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]:     at Object.onConfigChanged (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/app.js:42:16)
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]:     at process.<anonymous> (/opt/c3985ad0-be13-11eb-856f-1da0e30d2c5a-live/matrix-appservice-irc-develop-26-05-21-libera/node_modules/matrix-appservice-bridge/lib/components/cli.js:232:35)
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]:     at process.emit (events.js:376:20)
May 26 21:31:26 eu-west-2-ircbridges liberairc[24311]:     at process.emit (domain.js:470:12)
```

**Comment by tadzik** [comment]
Seems to have been fixed by a11d70f02cd4dd055d3f964dee6c26af598ac1b0, doesn't reproduce anymore.
