### ISSUE TITLE
MatrixHandler::handleAdminRoomInvite exception handler is throwing due to undefined properties

### ISSUE THREAD

**Issue by andir** [matrix-org/matrix-appservice-irc#1346]
**Describe the bug**
I believe the error logging code in the `MatrixHandler::handleAdminRoomInvite` function is actually wrong in this line:
https://github.com/matrix-org/matrix-appservice-irc/blob/df0d2c8a23e01513a829c0d8a1ac411de32b6c92/src/bridge/MatrixHandler.ts#L139

During testing on a hackint test instance of the bridge we did observe the above mentioned line throw because the attribute `data` doesn't exist on the exception that was caught. Unfortunately I can't tell which exception from the logs we have.

```
1438362-May 27 01:30:45 matrix matrix-appservice-irc[13299]: 2021-05-27 01:30:45 ERROR:main TypeError: Cannot read property 'error' of undefined
1438363:May 27 01:30:45 matrix matrix-appservice-irc[13299]:     at MatrixHandler.handleAdminRoomInvite (/nix/store/5cb5prvqiq1zzp3kp7s3f1iaqr1xg59i-node_matrix-appservice-irc-0.26.0/lib/node_modules/matrix-appservice-irc/lib/bridge/MatrixHandler.js:69:93)
1438364-May 27 01:30:45 matrix matrix-appservice-irc[13299]:     at runMicrotasks (<anonymous>)
1438365-May 27 01:30:45 matrix matrix-appservice-irc[13299]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**
1. We had some intermediary configuration that I can't recall, sorry
2. Tried to join an IRC channel via the matrix bridge (from the matrix side)
3. The AppService would throw the above exception when trying to invite you.

**Expected behavior**

The error message (including the exception body?) should be logged and not cause another exception.

**Comment by andir** [comment]
Apparently related to https://github.com/matrix-org/matrix-appservice-irc/issues/1270 as that contains similar output from other users.

**Comment by Half-Shot** [comment]
It looks bad, but it's not the same as #1270. I've posted a solution to that one.

**Comment by lhorace** [comment]
It's Jan 2022, there's no fix? I dunno but this seems trivial to fix no? For those who come here, wondering what to do:

```diff
--- MatrixHandler.js.original   2022-01-08 09:34:16.830231247 -0500
+++ MatrixHandler.js    2022-01-08 09:23:30.582026773 -0500
@@ -78,7 +78,8 @@
             }
         }
         catch (err) {
-            req.log.debug(`Not a plumbed room: Error retrieving m.room.plumbing (${err.data.error})`);
+            //req.log.debug(`Not a plumbed room: Error retrieving m.room.plumbing (${err.data.error})`);
+            req.log.debug(`Not a plumbed room: Error retrieving m.room.plumbing (FIXME)`);
         }
         // clobber any previous admin room ID
         await this.ircBridge.getStore().storeAdminRoom(mxRoom, inviter.userId);
```
