### ISSUE TITLE
Fatal exception: cli.isDead is not a function

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#152]
On https://github.com/matrix-org/matrix-appservice-irc/blob/0.4.0/lib/irc/ClientPool.js#L99
```
2016-08-31 01:24:28 ERROR:main FATAL EXCEPTION
2016-08-31 01:24:28 ERROR:main TypeError: cli.isDead is not a function
    at ClientPool.getBridgedClientByNick (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/ClientPool.js:99:21)
    at createUser (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/IrcEventBroker.js:253:24)
    at /home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/IrcEventBroker.js:320:30
    at Array.forEach (native)
    at IrcEventBroker.<anonymous> (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/IrcEventBroker.js:317:15)
    at Function.<anonymous> (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/IrcEventBroker.js:226:20)
    at Client.<anonymous> (/home/ircas/matrix-org/freenode/matrix-appservice-irc/lib/irc/ConnectionInstance.js:109:12)
    at emitMany (events.js:108:13)
    at Client.emit (events.js:182:7)
    at Client.<anonymous> (/home/ircas/matrix-org/freenode/matrix-appservice-irc/node_modules/irc/lib/irc.js:613:22)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at iterator (/home/ircas/matrix-org/freenode/matrix-appservice-irc/node_modules/irc/lib/irc.js:836:26)
    at Array.forEach (native)
    at Socket.<anonymous> (/home/ircas/matrix-org/freenode/matrix-appservice-irc/node_modules/irc/lib/irc.js:831:15)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

```
$ git status
# On branch v0.4.0
```

**Comment by Kegsay** [comment]
Because we're muppets and not using an actual ES6 `Map`, so default Object builtins are of course not `undefined`.

**Comment by Kegsay** [comment]
Used `Object.create(null)` instead as ES6 Maps change how you set/get from the map (functions instead) and I don't fancy updating alllll the places. Hotfixed on the matrix.org Freenode bridge.
