### ISSUE TITLE
setting joinChannelsIfNoUsers to false crashes the bridge

### ISSUE THREAD

**Issue by poVoq** [matrix-org/matrix-appservice-irc#1667]
```
        # Join channels even if there are no Matrix users on the other side of
        # the bridge. Set to false to prevent the bot from joining channels which have no
        # real matrix users in them, even if there is a mapping for the channel.
        # Default: true
        joinChannelsIfNoUsers: true
```
If I set this to false as instructed the bridge fails to start with this error:

```
2023-02-25 02:23:57 ERROR:CLI Failed to run bridge.
2023-02-25 02:23:57 ERROR:CLI Error: {"length":91,"name":"error","severity":"ERROR","code":"42601","position":"69","file":"scan.l","line":"1188","routine":"scanner_yyerror"}
2023-02-25 02:23:57 ERROR:CLI error: syntax error at or near "$1"
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by progval** [comment]
Syntax error in a dependency? Looks like `pg-protocol` expects a newer Nodejs version than what you have

**Comment by poVoq** [comment]
I use the official Docker image.
