### ISSUE TITLE
Cannot join rooms that start with a '&'

### ISSUE THREAD

**Issue by tfreedman** [matrix-org/matrix-appservice-irc#278]
I'd like to bridge an instance of Bitlbee (an IRC <-> everything other protocol bridge) using matrix-appservice-ircd, which would allow me to use Matrix to talk to people on things like Skype / Google Hangouts. (While obviously going from Matrix <-> IRC <-> Hangouts isn't ideal, it does allow me to use a single client and not have to worry about the state of various other matrix bridge projects, since this one appears to be the mature). My configuration is set up to whitelist only myself (for obvious privacy reasons), and to bridge a single matrix room to the Bitlbee control channel, which is a room that you get force-joined to upon connecting to the server.

Unfortunately, the Bitlbee control channel is called '&bitlbee', and rooms that don't start with a # will be rejected in various ways by matrix-appservice-irc:

In IRC Admin Room:
!join localhost &bitlbee
> Format: '!join irc.example.com #channel [key]'

In logs:
> 2016-11-05 01:54:39 ERROR:req [4bikfj5fft0k8] [I->M] Cannot route PM to &bitlbee (null@localhost)

In the config file, upon boot:
```
Loading config file /home/tyler/.synapse/matrix-appservice-irc/config.yaml
{"instanceContext":"#/ircService/servers/localhost/mappings","resolutionScope":"anon-schema://8b4bb394aee20d180017ba591a723b4b5be6f69a/#/properties/ircService/properties/servers/additionalProperties/properties/mappings","constraintName":"additionalProperties","testedValue":"&bitlbee","desc":"property \"&bitlbee\" not allowed by \"properties\" or by \"patternProperties\" and \"additionalProperties\" is false","kind":"ObjectValidationError"}
/home/tyler/.synapse/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:47
        throw e;
        ^

Error: Failed to validate file
    at ConfigValidator.validate (/home/tyler/.synapse/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/config-validator.js:45:17)
    at Cli._loadConfig (/home/tyler/.synapse/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:159:22)
    at Cli._assignConfigFile (/home/tyler/.synapse/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:144:23)
    at Cli.run (/home/tyler/.synapse/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/cli.js:138:10)
    at Object.<anonymous> (/home/tyler/.synapse/matrix-appservice-irc/app.js:28:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

The Bitlbee FAQ specifically covers this edge case (see the last question on https://wiki.bitlbee.org/FAQ), and suggests that IRC clients that have trouble connecting to rooms that start with a '&' are client bugs and should be reported to the IRC client developers.

**Comment by TJuberg** [comment]
For the record

RFC1459 Channel prefixes:
& Server local channel, nothing about this channel will be propogated to any other server.
# Network channel

RFC2811 Channel prefixes:
! Network Safe channel
+ Network unmoderated channel

The 005 numeric sent on connection can also be used for IRCd's supporting it to determine valid prefixes
:irc.example.org 005 nick PREFIX=(ov)@+ CHANTYPES=#& :are supported by this server

**Comment by Kegsay** [comment]
From the same Bitlbee link:

> You can create a new control channel with a different name, see "help channel". 

We are aware that the bridge only supports `#`. We have no plans at this time to work on changing that behaviour because it works for our use case and our time is spent on [different problems](https://github.com/matrix-org/matrix-appservice-irc/issues?q=is%3Aissue+is%3Aopen+label%3Abug). I appreciate this is not a great response, but we need to draw lines in the sand somewhere.

PRs to fix this issue will be most welcome.

**Comment by Spydar007** [comment]
Other prefixes include `!`, `+`, and `%`

**Comment by Spydar007** [comment]
Also worth noting that the supported channel types on a server can be determined by `CHANTYPES`, accessed through the 005 `ISUPPORT` numeric (and sometimes 351 `VERSION`)

**Comment by ptman** [comment]
@maakuth has that fixed worked for you in production?

**Comment by maakuth** [comment]
Nope, unfortunately it's not the complete fix. I have not had the resources to dig deeper into it, sorry to say.
