### ISSUE TITLE
Using IPv6-Prefix yields bind: EINVAL

### ISSUE THREAD

**Issue by Nebukadneza** [matrix-org/matrix-appservice-irc#292]
When using the (great!) IPv6-Prefix feature, using something like:

`
    #   ircClients:
    #     ipv6:
    #       prefix: "2a01:238:42e5:ac00::"
`

I’m getting the following in the error logs:

`
2016-11-29 08:38:13 ERROR:client-connection Server: irc.uni-erlangen.de (foo) Network Error: {
  "code": "EINVAL",
  "errno": "EINVAL",
  "syscall": "bind",
  "address": "2a01:238:42e5:ac00::2"
}
`

The address chosen is also set on the interface. Interestingly, when stracing with 
`
strace -o log -f -e socket,bind,setsockopt,connect,write -s 99999999 app.js -c config.yaml -f appservice-registration-irc.yaml […]
`
Then i can find no bind that fails with EINVAL! That’s rather strange, so … is there a component in-between that’s „faking“ syscalls and return values?

Thanks for this great feature btw ^_^.

**Comment by Kegsay** [comment]
You need to have a pool of IPv6 addresses at your disposal. You need to be running the IRC bridge on a box which supports [IP_FREEBIND](http://man7.org/linux/man-pages/man7/ip.7.html). Annoyingly Node.js doesn't grant me the ability to `setsockopt` so there's some degree of hackery to get it all working if you're running on an older kernel. Ideally you'd be running on a newer kernel which just natively supports all this.

**Comment by Kegsay** [comment]
You may also need to set up your routing tables so you can bind to it, e.g:
```
$ ip route add local 2001:560:2f2a:100::/64 dev lo
```

In our experience, you cannot bind to a huge subnet (like `/56` and above), it just silently fails on Linux. You also may want to bump your `net.ipv6.route.max_size` in sysctl if you plan on having thousands of connections.

**Comment by NebuKatWork** [comment]
For the record, in the matrix-room, LeoNerd told me that
https://github.com/matrix-org/freebindfree
is required as a LD_PRELOAD for node.

I’ll leave some more comments when i get it to work, and how.

**Comment by Kegsay** [comment]
> I’ll leave some more comments when i get it to work, and how.

Please do!

**Comment by Nebukadneza** [comment]
Hi,

i still don’t have it working, unfortunatly. Let’s summarize:

I have a more current node now, which should not have that ipv6 bind bug anymore:
`
> node --version
v6.9.1
`

My config (excerpt) looks like this:
`
    irc6.de.ircnet.net:
      port: 6667
      ssl: false
      sslselfsign: false
      sendConnectionMessages: true
      botConfig:
        enabled: false
        nick: "GhostMatrix"
        joinChannelsIfNoUsers: false
      privateMessages:
        enabled: true
        federate: false
      dynamicChannels:
        enabled: true
        aliasTemplate: "#irc_ircnet_$CHANNEL"
        createAlias: true
        published: false
        joinRule: public
        federate: false
      membershipLists:
        enabled: true
        global:
          ircToMatrix:
            initial: true
            incremental: true
          matrixToIrc:
            initial: true
            incremental: true
      matrixClients:
        userTemplate: "@ircnet_$NICK"
        displayName: "M-$NICK"
      ircClients:
        ipv6:
          prefix: "2a01:238:42e5:ac00::"
        nickTemplate: "$DISPLAY"
        allowNickChanges: true
        maxClients: 30
        idleTimeout: 604800
        lineLimit: 3
`

The used host resolves *only* on v6:
`
> host irc6.de.ircnet.net
irc6.de.ircnet.net has IPv6 address 2001:638:a00:6667::53
irc6.de.ircnet.net has IPv6 address 2001:41b8:205::250
`

I have not set (one of the) IP used by the bridge explicitly on the interface:
`
> ip -6 -o a l | grep 2a01:238:42e5:ac00::85
`

However, I have added a route for my complete subnet:
`
ip -6 -o r | grep '/56'
2a01:238:42e5:ac00::/56 dev eth0  proto kernel  metric 256 
`

I’m starting the bridge like
`
LD_PRELOAD=freebindfree/libfreebindfree.so node app.js -c config.yaml -f appservice-registration-irc.yaml -p 9999
`
using your freebind PRELOAD.


To test, I’ve started the bridge with ONLY the v6 server setup
`
Loading config file /opt/matrix-appservice-irc/config.yaml
2016-12-04 15:13:11 INFO:DataStore Indexes checked on 'id' for store.
2016-12-04 15:13:11 INFO:DataStore Indexes checked on 'matrix_id' for store.
2016-12-04 15:13:11 INFO:DataStore Indexes checked on 'remote_id' for store.
2016-12-04 15:13:11 INFO:DataStore Indexes checked on 'localpart' for store.
2016-12-04 15:13:11 INFO:DataStore Indexes checked on 'user id' for store.
2016-12-04 15:13:11 DEBUG:DataStore removeConfigMappings
2016-12-04 15:13:11 DEBUG:DataStore setServerFromConfig
2016-12-04 15:13:11 INFO:IrcBridge Joining mapped Matrix rooms...
2016-12-04 15:13:11 DEBUG:DataStore getRoomIdsFromConfig
2016-12-04 15:13:11 INFO:IrcBridge Syncing relevant membership lists...
2016-12-04 15:13:11 INFO:MemberListSyncer Checking membership lists for syncing on irc6.de.ircnet.net
2016-12-04 15:13:11 INFO:IrcBridge [-] GET http://ghostdub.de:8008/_matrix/client/r0/sync (AS) Body:
2016-12-04 15:13:11 INFO:Provisioner Provisioning disabled.
2016-12-04 15:13:11 INFO:IrcBridge Connecting to IRC networks...
2016-12-04 15:13:11 DEBUG:ClientPool 0 active connections on irc6.de.ircnet.net
2016-12-04 15:13:11 DEBUG:IrcBridge Created new bot client for irc6.de.ircnet.net : j99xvmaqdygo4 (bot enabled=false)
2016-12-04 15:13:11 INFO:IrcBridge Bot connecting to irc6.de.ircnet.net (0 channels) => []
2016-12-04 15:13:11 INFO:Ipv6Generator Retrieving counter...
2016-12-04 15:13:11 DEBUG:DataStore getIpv6Counter
2016-12-04 15:13:11 INFO:Ipv6Generator Enqueueing IPv6 generation request for matrixirc
2016-12-04 15:13:11 DEBUG:DataStore setIpv6Counter
2016-12-04 15:13:11 INFO:BridgedClient <GhostMatrix@irc6.de.ircnet.net#j99xvmaqdygo4> Connecting to IRC server irc6.de.ircnet.net as GhostMatrix (user=matrixirc)
2016-12-04 15:13:11 INFO:client-connection Scheduling disabled for GhostMatrix on irc6.de.ircnet.net, retrying with delay 1701ms (attempts 1)
2016-12-04 15:13:11 DEBUG:irc-ident Set user matrixirc on port 44527
2016-12-04 15:13:13 INFO:IrcBridge [-] GET http://ghostdub.de:8008/_matrix/client/r0/sync (AS) HTTP 200 {"next_batch":"s154296_509986_2598_14396_119_25_241","rooms":{"leave":{},"j
oin":
2016-12-04 15:13:13 INFO:MemberListSyncer Found 14 syncable rooms (1948ms)
2016-12-04 15:13:13 INFO:MemberListSyncer Joining Matrix users to IRC channels...
2016-12-04 15:13:13 DEBUG:MemberListSyncer 14 rooms passed the config rules
2016-12-04 15:13:13 DEBUG:MemberListSyncer Got 14 matrix join events to inject.

[ probably private stuff here ]


2016-12-04 15:14:14 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net still not connected after 30000ms. Killing connection.
2016-12-04 15:14:14 INFO:client-connection disconnect()ing GhostMatrix@irc6.de.ircnet.net - timeout
2016-12-04 15:14:15 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net RECV a notice event for a dead connection
2016-12-04 15:14:15 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: GhostMatrix[~matrixirc@2a01:238:42e5:ac00:0:0:0:8a] (\"timeout\")"]}
2016-12-04 15:14:15 DEBUG:ClientPool onClientDisconnected: <j99xvmaqdygo4> Reconnecting GhostMatrix@irc6.de.ircnet.net in 1000ms
2016-12-04 15:14:15 DEBUG:ClientPool 0 active connections on irc6.de.ircnet.net
2016-12-04 15:14:15 DEBUG:BridgedClient <GhostMatrix@irc6.de.ircnet.net#j99xvmaqdygo4> connected!
2016-12-04 15:14:15 DEBUG:BridgedClient <GhostMatrix@irc6.de.ircnet.net#j99xvmaqdygo4> _keepAlive; Restarting 604800s idle timeout
2016-12-04 15:14:15 DEBUG:DataStore getTrackedChannelsForServer irc6.de.ircnet.net
2016-12-04 15:14:15 INFO:IrcBridge Startup complete.
2016-12-04 15:14:15 INFO:PublicitySyncer Bot requesting mode for #gnuher.de on irc6.de.ircnet.net
2016-12-04 15:14:16 ERROR:client-connection Nebukadneza@irc6.de.ircnet.net still not connected after 30000ms. Killing connection.
2016-12-04 15:14:16 INFO:client-connection disconnect()ing Nebukadneza@irc6.de.ircnet.net - timeout
2016-12-04 15:14:16 INFO:Ipv6Generator Using existing IPv6 address 2a01:238:42e5:ac00::8a for %s
2016-12-04 15:14:16 INFO:BridgedClient <GhostMatrix@irc6.de.ircnet.net#dyuadbw8z8ws0> Connecting to IRC server irc6.de.ircnet.net as GhostMatrix (user=matrixirc)
2016-12-04 15:14:16 INFO:scheduler Queued scheduled promise for irc6.de.ircnet.net GhostMatrix
2016-12-04 15:14:16 INFO:scheduler Queue for irc6.de.ircnet.net length = 1
2016-12-04 15:14:17 ERROR:client-connection Nebukadneza@irc6.de.ircnet.net Timed out waiting for disconnect callback
2016-12-04 15:14:17 ERROR:main Error: Timed out when calling client.disconnect()
    at Timeout.setTimeout (/opt/matrix-appservice-irc/lib/irc/ConnectionInstance.js:118:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2016-12-04 15:14:18 ERROR:client-connection retryFailed after 2 attempts (timeout)
2016-12-04 15:14:18 INFO:scheduler Queued scheduled promise for irc6.de.ircnet.net Nebukadneza
2016-12-04 15:14:18 INFO:scheduler Queue for irc6.de.ircnet.net length = 2
2016-12-04 15:14:21 DEBUG:irc-ident Set user matrixirc on port 38974
2016-12-04 15:14:51 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net still not connected after 30000ms. Killing connection.
2016-12-04 15:14:51 INFO:client-connection disconnect()ing GhostMatrix@irc6.de.ircnet.net - timeout
2016-12-04 15:14:52 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net Timed out waiting for disconnect callback
2016-12-04 15:14:52 ERROR:client-connection retryFailed after 1 attempts (timeout)
2016-12-04 15:14:52 INFO:scheduler Queued scheduled promise for irc6.de.ircnet.net GhostMatrix
2016-12-04 15:14:52 INFO:scheduler Queue for irc6.de.ircnet.net length = 2
2016-12-04 15:14:52 ERROR:main Error: Timed out when calling client.disconnect()
    at Timeout.setTimeout (/opt/matrix-appservice-irc/lib/irc/ConnectionInstance.js:118:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2016-12-04 15:14:55 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net RECV a notice event for a dead connection
2016-12-04 15:14:55 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net: {"command":"ERROR","rawCommand":"ERROR","commandType":"normal","args":["Closing Link: GhostMatrix[~matrixirc@2a01:238:42e5:ac00:0:0:0:8a] (\"timeout\")"]}
2016-12-04 15:14:55 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net disconnect callback invoked too late
2016-12-04 15:15:20 ERROR:client-connection Server: irc6.de.ircnet.net (Nebukadneza) Network Error: {
  "code": "ETIMEDOUT",
  "errno": "ETIMEDOUT",
  "syscall": "connect",
  "address": "2001:638:a00:6667::53",
  "port": 6667
}
2016-12-04 15:15:27 ERROR:client-connection Nebukadneza@irc6.de.ircnet.net still not connected after 30000ms. Killing connection.
2016-12-04 15:15:27 INFO:client-connection disconnect()ing Nebukadneza@irc6.de.ircnet.net - timeout
2016-12-04 15:15:28 ERROR:client-connection Nebukadneza@irc6.de.ircnet.net Timed out waiting for disconnect callback
2016-12-04 15:15:28 ERROR:client-connection retryFailed after 3 attempts (timeout)
2016-12-04 15:15:28 INFO:scheduler Queued scheduled promise for irc6.de.ircnet.net Nebukadneza
2016-12-04 15:15:28 INFO:scheduler Queue for irc6.de.ircnet.net length = 2
2016-12-04 15:15:28 ERROR:main Error: Timed out when calling client.disconnect()
    at Timeout.setTimeout (/opt/matrix-appservice-irc/lib/irc/ConnectionInstance.js:118:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2016-12-04 15:15:53 ERROR:client-connection Server: irc6.de.ircnet.net (Nebukadneza) Network Error: {
  "code": "ETIMEDOUT",
  "errno": "ETIMEDOUT",
  "syscall": "connect",
  "address": "2001:638:a00:6667::53",
  "port": 6667
}


2016-12-04 15:16:03 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net still not connected after 30000ms. Killing connection.
2016-12-04 15:16:03 INFO:client-connection disconnect()ing GhostMatrix@irc6.de.ircnet.net - timeout
2016-12-04 15:16:04 ERROR:client-connection GhostMatrix@irc6.de.ircnet.net Timed out waiting for disconnect callback
2016-12-04 15:16:04 ERROR:client-connection retryFailed after 2 attempts (timeout)
2016-12-04 15:16:04 INFO:scheduler Queued scheduled promise for irc6.de.ircnet.net GhostMatrix
2016-12-04 15:16:04 INFO:scheduler Queue for irc6.de.ircnet.net length = 2
2016-12-04 15:16:04 ERROR:main Error: Timed out when calling client.disconnect()
    at Timeout.setTimeout (/opt/matrix-appservice-irc/lib/irc/ConnectionInstance.js:118:20)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
2016-12-04 15:16:09 DEBUG:irc-ident Set user nebukadnez on port 38253
^C
`

While the connection attempts ran, i had only one unanswered connection open:
`
> netstat -n | grep 6667 | egrep '2001:638:a00:6667::53|2001:41b8:205::250'
tcp6       0      0 2a01:238:42e5:ac0:38974 2001:41b8:205::250:6667 TIME_WAIT
`

From a machine remote to the one running the bridge, i can ping any (not explicitly added/enumerated) address on my host-running-the-bridge, within the subnet, e.g.:
`
> ping6 2a01:238:42e5:ac00:12::342
PING 2a01:238:42e5:ac00:12::342(2a01:238:42e5:ac00:12::342) 56 data bytes
64 bytes from 2a01:238:42e5:ac00:12::342: icmp_seq=1 ttl=56 time=57.9 ms
> ping6 2a01:238:42e5:ac00:dead:beef::23
PING 2a01:238:42e5:ac00:dead:beef::23(2a01:238:42e5:ac00:dead:beef:0:23) 56 data bytes
64 bytes from 2a01:238:42e5:ac00:dead:beef:0:23: icmp_seq=1 ttl=56 time=61.5 ms
64 bytes from 2a01:238:42e5:ac00:dead:beef:0:23: icmp_seq=2 ttl=56 time=35.2 ms
> ping6 2a01:238:42e5:ac00::124
PING 2a01:238:42e5:ac00::124(2a01:238:42e5:ac00::124) 56 data bytes
64 bytes from 2a01:238:42e5:ac00::124: icmp_seq=1 ttl=56 time=60.6 ms
`

The last one is one address I’ve seen the bridge generate in the past …


Any tip would be highly appreciated at this time ^_^

Best & Thanks
-Dario

**Comment by Kegsay** [comment]
> In our experience, you cannot bind to a huge subnet (like /56 and above), it just silently fails on Linux.


> However, I have added a route for my complete subnet:
> ```
> ip -6 -o r | grep '/56'
> 2a01:238:42e5:ac00::/56 dev eth0  proto kernel  metric 256 
> ```

**Comment by Nebukadneza** [comment]
Hi,

I’m sorry i overlooked that part again! I have now added a smaller (/96) subnet, and reset the user.db — and removed any ipv6 in a users’ section, to be sure new addresses are getting generated from the new subnet.

I’ve also added the first few addresses it’d use manually to test, but it just won’t connect — the errorlog stays the same as above.

**Comment by Kegsay** [comment]
The fact that you're getting `ETIMEDOUT` indicates that your machine is probably sending a SYN but not getting a SYN-ACK back. If you're able to ping a random v6 address from a remote machine (I assume not on the same network!), then are you sure that the bridge is listening on the right interface?

**Comment by Nebukadneza** [comment]
Hi,

after long last, with your continued support, i got it to work! Yay!

The issue was a bit opaque, since it combined multiple problems. So my run of problems was:
- adding routes for too large subnets doesn’t work (already found above)
- if the hostname to connect to has an A and an AAAA record, ¿sometimes? the A gets chosen, but it’s tried to connect with an INET6 socket
- if the hostname hast 2 AAAA records of which one does not work … guess which one will get chosen for you (hint: when you try with irssi it’s the working one, on your server it’s the other one :D :D :D)
- it’s not possible to use an IPv6 as host/connection-target since it’s both the name used by the bot, and a yaml section header — containing ":"’s
- IRCNet takes darn long to process your connection — and the timeout for it (https://github.com/matrix-org/matrix-appservice-irc/blob/b8c784ff20d31d76e8c3f25a9a1424aca4fa2835/lib/irc/ConnectionInstance.js#L10) is not configurable in config


So, what i had to do to get it working for me — as a help for others:
1. Add a route for reasonably small subnet of your delegated IPv6 subnet `dead:beef:1234:2342::/96 dev ethX`
2. Add it to your config.yaml in the right network, such as:
`
      ircClients:
        ipv6:
          prefix: "2a01:238:42e5:ac00:0:2::"
`
3. Build https://github.com/matrix-org/freebindfree
4. Make sure your target host only answers to ONE IPv6 and NO IPv4. I had to create a subdomain on one of my own domains for this purpose:
`
$ host -t AAAA irc6fake.XXX.de
irc6fake.XXX.de has IPv6 address 2001:638:a000:1194:194::2
$ host -t A irc6fake.XXX.de
irc6fake.XXX.de has no A record
`
5. If your network is slow, like IRCNet, increase the connect timeout at https://github.com/matrix-org/matrix-appservice-irc/blob/b8c784ff20d31d76e8c3f25a9a1424aca4fa2835/lib/irc/ConnectionInstance.js#L10
6. If you‘ve tried around with other IPv6 subnets before, make sure data/users.db contains no leftover randomized-IPv6 for any of your users. Remove them manually when your subnet has changed!
7. Make sure you use freebindfree to start your bridge — parameters depend on your usecase, but something like: `LD_PRELOAD=/path/to/freebindfree/libfreebindfree.so node app.js -c config.yaml -f appservice-registration-irc.yaml -p 9999`
8. Finally see the connection message and Enjoy!

I think i’ll close this issue with this, and will open issues for what i think might make the bridge even better.

And last but not least: Thank you for this great project, and your good support with this!
Best
-Dario
