### ISSUE TITLE
Syntax error on master

### ISSUE THREAD

**Issue by matthiasbeyer** [matrix-org/matrix-appservice-irc#356]
Hi,

I just tried to follow the README and it gets me to:

```
/home/sysadmin/irc-bridge/matrix-appservice-irc/app.js:7
const REG_PATH = "appservice-registration-irc.yaml";
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by Kegsay** [comment]
Please let me know:
```
$ node -v
$ npm -v
```

and what command you are running to start the bridge.

**Comment by matthiasbeyer** [comment]
```
$ node -v
v0.10.29

$ npm -v
1.4.21
```

I'm doing `node app.js --help`.

**Comment by matthiasbeyer** [comment]
My mistake. Debian has not only old nodejs, but f*****g old nodejs.
