### ISSUE TITLE
Unable to install on node 6

### ISSUE THREAD

**Issue by ptman** [matrix-org/matrix-appservice-irc#381]
The command

    npm install matrix-appservice-irc --global

works on node 4, but not on node 6

**Comment by lukebarnard1** [comment]
Have you got any logs for this?

**Comment by ptman** [comment]
$ docker run --rm -it alpine sh
    # apk update
    # apk add build-base nodejs git icu-dev python2
    # npm install matrix-appservice-irc --global
    ...

```
  CXX(target) Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o
In file included from ../../nan/nan.h:182:0,
                 from ../node-icu-charset-detector.cpp:2:
../../nan/nan_maybe_43_inl.h: In function 'Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)':
../../nan/nan_maybe_43_inl.h:221:58: warning: 'v8::MaybeLocal<v8::Object> v8::Array::CloneElementAt(v8::Local<v8::Context>, uint32_t)' is deprecated: Cloning is not supported. [-Wdeprecated-declarations]
   return array->CloneElementAt(GetCurrentContext(), index);
                                                          ^
In file included from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/node.h:42,
                 from ../node-icu-charset-detector.cpp:1:
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:3032:36: note: declared here
                 MaybeLocal<Object> CloneElementAt(Local<Context> context,
                                    ^
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:188,
                 from ../node-icu-charset-detector.cpp:2:
../../nan/nan_implementation_12_inl.h: In static member function 'static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)':
../../nan/nan_implementation_12_inl.h:40:38: warning: 'static v8::Local<v8::Value> v8::BooleanObject::New(bool)' is deprecated: Pass an isolate [-Wdeprecated-declarations]
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/node.h:42,
                 from ../node-icu-charset-detector.cpp:1:
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:4007:56: note: declared here
   V8_DEPRECATED("Pass an isolate", static Local<Value> New(bool value));
                                                        ^
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../node-icu-charset-detector.cpp:2:0:
../../nan/nan.h: At global scope:
../../nan/nan.h:590:20: error: variable or field 'AddGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:590:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:591:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:596:20: error: variable or field 'RemoveGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:596:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:601:20: error: variable or field 'AddGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:601:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:602:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:607:20: error: variable or field 'RemoveGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:607:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback) {
       ^~
../../nan/nan.h: In function 'bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)':
../../nan/nan.h:1933:16: warning: 'bool v8::Object::SetAccessor(v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)' is deprecated: Use maybe version [-Wdeprecated-declarations]
     , attribute);
                ^
In file included from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/node.h:42,
                 from ../node-icu-charset-detector.cpp:1:
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8.h:2751:22: note: declared here
                 bool SetAccessor(Local<Name> name,
                      ^
/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
make: *** [node-icu-charset-detector.target.mk:92: Release/obj.target/node-icu-charset-detector/node-icu-charset-detector.o] Error 1
make: Leaving directory '/usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.0-1-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/matrix-appservice-irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v6.9.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by Kegsay** [comment]
matrix.org is running the IRC bridge on:
```
$ node -v
v6.9.2
```
so it's not broken. The error you've pasted is to do with `node-icu-charset-detector` which is an optional dependency: it'll work without it.

**Comment by ptman** [comment]
Great, thanks

**Comment by vext01** [comment]
I had the same with v7.10.0 on debian 8. Seems that module is still busted...

**Comment by mcrosson** [comment]
To those finding this thread later. I ran the following command from the root of the sources. It wasn't immediately obvious the failure was coming from node-irc or that iconv and node-gyp were wholly optional. This is the best I could figure out for getting the build to work.

npm install --save --no-optional node-icu-charset-detector

npm install node-irc --no-optional --global

npm install matrix-appservice-irc --global --no-optional
