### ISSUE TITLE
Unexplained pauses in traffic/logs

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/matrix-appservice-irc#394]
> I->M traffic looks weird. Very spikey (periods of 0, then compensatory periods of high rates). cpu and ram look okay

Checking the logs, there are periods of nothing:
```
2017-03-15 19:44:57 INFO:client-connection disconnect()ing gnos-M@irc.mozilla.org - timeout
2017-03-15 19:44:59 ERROR:client-connection gnos-M@irc.mozilla.org Timed out waiting for disconnect callback
2017-03-15 19:48:20 DEBUG:IrcEventBroker bloodaxe-M is claiming a hash for cmd PRIVMSG
```

```
2017-03-15 21:04:20 ERROR:client-connection lime_-M@irc.mozilla.org Timed out waiting for disconnect callback
2017-03-15 21:04:29 INFO:IrcBridge [2d6zs9889ou80] DELAYED (10193ms)
2017-03-15 21:05:53 DEBUG:IrcEventBroker SpEcHiDeR is claiming a hash for cmd QUIT
```

```
2017-03-15 21:06:32 ERROR:client-connection koschei-M@irc.mozilla.org Timed out waiting for disconnect callback
2017-03-15 21:07:55 ERROR:IrcBridge [-] PUT http://matrix.org/_matrix/client/r0/presence/%40mozilla_bhearsum%3Amatrix.org/status (@mozilla_bhearsum:matrix.org) HTTP null Error: {"code":"ETIMEDOUT","connect":true
```

It sounds as if the event loop isn't given any chance to run (which explains why no logs, explains why there is no cpu spin, and explains why there is no bridged traffic), but bizarrely the `/metrics` listener *was* working up to a point, but are logged waaaaay later all together:
```
2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"

2017-03-15 21:08:05 INFO:IrcBridge ::ffff:xx.xx.xx.xx - - [15/Mar/2017:21:08:05 +0000] "GET /metrics HTTP/1.1" 200 8785 "-" "Go-http-client/1.1"
```

There's a characteristic correlation between cpu spiking and GC, which does admittedly match the event loop lag, and it was approaching it's heap limit, so can it really be chalked up to GC?

**Comment by Kegsay** [comment]
Hijacking this issue to diagnose CPU spin, as it behaves in a similar enough way (unexplained pauses then all the logs suddenly come through). This appears to be correlated with network connectivity issues to IRC (lots of mass disconnects), but whether that is a cause or effect I don't know.

During this time, no logs are made, but when it eventually recovers the next log line is uninteresting (it's not like it was stuck spinning in a while loop). It's almost as if the event loop is being starved in favour of network I/O? I got a `gdb` dump when this happens (since it won't even respond to SIGUSR1 for the Node debugger). I tried to sample some stacks in v8 land and this is what I got:
```
Object.keys

v8::internal::Runtime_CreateDataProperty(int, v8::internal::Object**, v8::internal::Isolate*) ()

#5  0x0000000000e713c9 in v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) ()
#6  0x000000000116ad88 in v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) ()

#5  0x0000000000fc2617 in v8::internal::LookupIterator::Delete() ()
#6  0x0000000001004778 in v8::internal::JSReceiver::DeleteProperty(v8::internal::LookupIterator*, v8::internal::LanguageMode) ()
#7  0x000000000117c26b in ?? ()
#8  0x0000000001187f6d in v8::internal::Runtime_DeleteProperty_Sloppy(int, v8::internal::Object**, v8::internal::Isolate*) ()

#5  0x0000000000e77eb5 in v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) ()
#6  0x00000000011ebc44 in v8::internal::IncrementalStringBuilder::IncrementalStringBuilder(v8::internal::Isolate*) ()
#7  0x0000000000fa5a69 in v8::internal::JsonStringifier::JsonStringifier(v8::internal::Isolate*) ()
#8  0x0000000000b20a5c in v8::internal::Builtin_JsonStringify(int, v8::internal::Object**, v8::internal::Isolate*) ()

#16 0x0000000001022700 in v8::internal::JSReceiver::CreateDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::ShouldThrow) ()
#17 0x000000000118ac96 in v8::internal::Runtime_CreateDataProperty(int, v8::internal::Object**, v8::internal::Isolate*) ()

#110 0x0000000000a1b4ae in v8::internal::FixedArray::set(int, v8::internal::Object*) ()
```

aka calls to `Object.keys` and `JSON.stringify` and setting/deleting properties on objects. The stringify bit is interesting since we don't tend to do that in many places. Worth investigating.

**Comment by Half-Shot** [comment]
Closing as probably no longer relevant.
