### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by git-minix** [matrix-org/matrix-appservice-irc#487]
Debian 8

I'd followed the instructions
$ git clone https://github.com/matrix-org/matrix-appservice-irc.git
$ cd matrix-appservice-irc
$ npm install
$ npm test

> matrix-appservice-irc@0.8.0 test /user1/git/matrix-appservice-irc
> BLUEBIRD_DEBUG=1 jasmine --stop-on-failure=true

/user1/git/matrix-appservice-irc/spec/integ/MemberListSyncer.spec.js:2
let test = require("../util/test");
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /user1/git/matrix-appservice-irc/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (native)
    at Jasmine.loadSpecs (/user1/git/matrix-appservice-irc/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/user1/git/matrix-appservice-irc/node_modules/jasmine/lib/jasmine.js:197:8)
npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

===============

On debian there is a known issue with the node binary.

I've used the work around ln -s /usr/bin/nodejs /usr/local/bin/node  to cover this. But also with the other approach (# apt remove nodejs-legacy) npm test shows the same error.

**Comment by git-minix** [comment]
fixed with upgrade to nodejs v6.11.3
