### ISSUE TITLE
Bridge crashes when talking to psyced.net

### ISSUE THREAD

**Issue by intelfx** [matrix-org/matrix-appservice-irc#536]
The bridge crashes when talking to ircs://psyced.net:6697 (I have no idea what exactly causes the crash, but this is the first time I've seen it):

```
янв 04 13:52:40 server systemd[1]: Started synapse-irc.service.
янв 04 13:52:41 server matrix-appservice-irc[29276]: Loading config file /etc/synapse/irc/config.yaml
янв 04 13:52:44 server matrix-appservice-irc[29276]: 4 Jan 13:52:44 - UNABLE_TO_GET_ISSUER_CERT_LOCALLY
янв 04 13:52:48 server matrix-appservice-irc[29276]: /home/operator/matrix-appservice-irc/node_modules/olm/olm.js:19
янв 04 13:52:48 server matrix-appservice-irc[29276]: "undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module object]"}}else if(ma)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},a.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");z("object"===typeof a);return a},"undefined"!=
янв 04 13:52:48 server matrix-appservice-irc[29276]:                                                                                                                 ^
янв 04 13:52:48 server matrix-appservice-irc[29276]: TypeError: Cannot read property 'length' of undefined
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client._splitMessage (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:1143:58)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client._speak (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:1158:28)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.notice (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:1138:10)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.ctcp (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:1259:55)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.<anonymous> (/home/operator/matrix-appservice-irc/lib/irc/ConnectionInstance.js:268:20)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.emit (events.js:159:13)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client._handleCTCP (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:1251:14)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.<anonymous> (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:609:26)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Client.emit (events.js:164:20)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at iterator (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:916:26)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at Array.forEach (<anonymous>)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at TLSSocket.<anonymous> (/home/operator/matrix-appservice-irc/node_modules/irc/lib/irc.js:911:15)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at TLSSocket.emit (events.js:159:13)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at addChunk (_stream_readable.js:265:12)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at readableAddChunk (_stream_readable.js:248:13)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at TLSSocket.Readable.push (_stream_readable.js:209:10)
янв 04 13:52:48 server matrix-appservice-irc[29276]:     at TLSWrap.onread (net.js:608:20)
янв 04 13:52:48 server systemd[1]: synapse-irc.service: Main process exited, code=exited, status=7/NOTRUNNING
янв 04 13:52:48 server systemd[1]: synapse-irc.service: Failed with result 'exit-code'.
янв 04 13:52:48 server systemd[1]: synapse-irc.service: Service hold-off time over, scheduling restart.
янв 04 13:52:48 server systemd[1]: synapse-irc.service: Scheduled restart job, restart counter is at 1.
янв 04 13:52:48 server systemd[1]: Stopped synapse-irc.service.
```

**Comment by Half-Shot** [comment]
@intelfx is this still the case?

**Comment by Half-Shot** [comment]
No response since. Closing.
