### ISSUE TITLE
Crash due to a type error in olm.js

### ISSUE THREAD

**Issue by pacien** [matrix-org/matrix-appservice-irc#540]
Bug happening shortly after upgrading from 0.7.2 to 0.8.0.
Running on NodeJS 4.8.7 on Debian 8.

Stacktrace/log:
```log
/usr/lib/node_modules/matrix-appservice-irc/node_modules/matrix-appservice-bridge/node_modules/matrix-js-sdk/node_modules/olm/olm.js:19
"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(a){if(!(a instanceof T))throw a;});a.inspect=function(){return"[Emscripten Module o
^
TypeError: Cannot read property 'match' of undefined
at Client.connect.Client._splitLongLines (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1111:10)
at /usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1148:25
at Array.map (native)
at Client.connect.Client._splitMessage (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1147:12)
at Client.connect.Client._speak (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1158:28)
at Client.connect.Client.notice (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1138:10)
at Client.connect.Client.ctcp (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1259:55)
at Client.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/lib/irc/ConnectionInstance.js:268:20)
at emitThree (events.js:97:13)
at Client.emit (events.js:175:7)
at Client.connect.Client._handleCTCP (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1251:14)
at Client.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:609:26)
at emitOne (events.js:82:20)
at Client.emit (events.js:169:7)
at iterator (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:916:26)
at Array.forEach (native)
at TLSSocket.<anonymous> (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:911:15)
at emitOne (events.js:77:13)
at TLSSocket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at TLSSocket.Readable.push (_stream_readable.js:111:10)
at TLSWrap.onread (net.js:540:20)
systemd[1]: matrix-appservice-irc.service: main process exited, code=exited, status=7/NOTRUNNING
systemd[1]: Unit matrix-appservice-irc.service entered failed state.
```

**Comment by Ralith** [comment]
I observed this as well, and had to roll back my update. Struck me as strange since the AS doesn't even use olm.

**Comment by Kegsay** [comment]
The bridge uses the JS SDK which includes Olm. Olm does "magic" to intercept stack traces, so the error here is unlikely to be referring to Olm. Most likely, the bug is at:
```
TypeError: Cannot read property 'match' of undefined
at Client.connect.Client._splitLongLines (/usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1111:10)
at /usr/lib/node_modules/matrix-appservice-irc/node_modules/irc/lib/irc.js:1148:25
at Array.map (native)
```

**Comment by pacien** [comment]
Still getting this error with matrix-appservice-irc 0.10.1.

**Comment by pacien** [comment]
The error disappeared after upgrading to 0.11.2 and starting with a new empty database.
