### ISSUE TITLE
IRC bridge failed to start: "Olm.get_library_version is not a function"

### ISSUE THREAD

**Issue by schiessle** [matrix-org/matrix-appservice-irc#709]
I'm trying to run my own IRC bridge. Installation was successfull and the test run also without an error, but when I start the bridge: `# node app.js -c config.yaml -f /opt/matrix-appservice-irc/appservice-registration-irc.yaml -p 9999` I get this error in the logfile:

````
2018-11-17 22:10:33 INFO:DataStore Indexes checked on 'matrix_id' for store.
2018-11-17 22:10:33 INFO:DataStore Indexes checked on 'remote_id' for store.
2018-11-17 22:10:33 INFO:DataStore Indexes checked on 'localpart' for store.
2018-11-17 22:10:33 INFO:DataStore Indexes checked on 'user id' for store.
2018-11-17 22:10:33 INFO:DataStore Private key loaded from passkey.pem - IRC password encryption enabled.
2018-11-17 22:10:33 INFO:DataStore Indexes checked for ident username for chat.freenode.net on users database
2018-11-17 22:10:33 ERROR:CLI Failed to run bridge.
2018-11-17 22:10:33 ERROR:main TypeError: Olm.get_library_version is not a function
    at Function.OlmDevice.getOlmVersion (/opt/matrix-appservice-irc/node_modules/matrix-js-sdk/lib/crypto/OlmDevice.js:218:16)
    at Function.Crypto.getOlmVersion (/opt/matrix-appservice-irc/node_modules/matrix-js-sdk/lib/crypto/index.js:341:22)
    at new MatrixClient (/opt/matrix-appservice-irc/node_modules/matrix-js-sdk/lib/client.js:281:34)
    at Object.module.exports.createClient (/opt/matrix-appservice-irc/node_modules/matrix-js-sdk/lib/matrix.js:188:10)
    at ClientFactory.getClientAs (/opt/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/components/client-factory.js:117:24)
    at Bridge.run (/opt/matrix-appservice-irc/node_modules/matrix-appservice-bridge/lib/bridge.js:230:43)
    at IrcBridge.<anonymous> (/opt/matrix-appservice-irc/lib/bridge/IrcBridge.js:312:24)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/generators.js:97:49)
    at _drainQueueStep (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
````

At the beginning I missed the olm package completely, then I followed this instruction: https://github.com/matrix-org/matrix-js-sdk#end-to-end-encryption-support

first installed the latest olm package: `npm install https://matrix.org/packages/npm/olm/olm-3.0.0.tgz` and add at the top of the app.js `global.Olm = require('olm');`

Any idea what's wrong here?

**Comment by schiessle** [comment]
ok, seems version 3.0.0 is to new, with 2.3.0 it works
