### ISSUE TITLE
Crash upon sending message from Matrix to IRC

### ISSUE THREAD

**Issue by peremen** [matrix-org/matrix-appservice-irc#869]
When I try to push a message from Matrix server to the IRC network, matrix-appservice-irc crashes with the following log. Other direction (IRC -> Matrix) works fine. I am using matrix-appservice-irc 0.13.0, node.js 12.13.0 and other components are pulled today. The network in question is [Ozinger](https://ozinger.org/).

```
2019-11-06 19:18:54 INFO:IrcBridge ::ffff:127.0.0.1 - - [06/Nov/2019:19:18:54 +0000] "PUT /transactions/104?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.5.0"

2019-11-06 19:18:54 INFO:req [snip] [M->I] m.room.message usr=(snip) rm=(snip) body=흐음콘
2019-11-06 19:18:54 INFO:req [snip] [M->I] Relaying message in (snip) on irc.ozinger.org
2019-11-06 19:18:54 INFO:IrcBridge [-] GET http://localhost:8008/_matrix/client/r0/rooms/(snip)state/m.room.member/(snip) (AS) Body: 
2019-11-06 19:18:54 INFO:IrcBridge [-] GET http://localhost:8008/_matrix/client/r0/rooms/(snip)/state/m.room.member/(snip) (AS) HTTP 200 "{\"membership\": \"join\", \"displayname\": \"peremem\", \"avatar_url\": null}"
2019-11-06 19:18:54 DEBUG:IrcBridge Configuring IRC user from store => (snip)=>irc.ozinger.org={"username":"peremenmat","nick":null}
2019-11-06 19:18:54 DEBUG:IrcBridge Creating virtual irc user with nick null for (snip) (display name peremem)
2019-11-06 19:18:54 DEBUG:ClientPool 2 active connections on irc.ozinger.org
2019-11-06 19:18:54 DEBUG:IdentGenerator Using cached ident username peremenmat for (snip) on irc.ozinger.org
2019-11-06 19:18:54 INFO:BridgedClient <snip> (snip) Connecting to IRC server irc.ozinger.org as peremem[m] (user=peremenmat)
2019-11-06 19:18:54 INFO:scheduler Queued scheduled promise for irc.ozinger.org peremem[m]
2019-11-06 19:18:54 INFO:scheduler Queue for irc.ozinger.org length = 1
2019-11-06 19:19:00 DEBUG:irc-ident Set user peremenmat on port 52674
2019-11-06 19:19:00 DEBUG:client-connection Received ping from k[GoxXdSeL directed at peremem[m]
2019-11-06 19:19:01 ERROR:req [(snip)] [I->M] Cannot route PM to peremem[m] (null@irc.ozinger.org) - no client
2019-11-06 19:19:01 DEBUG:BridgedClient <peremem[m]@irc.ozinger.org#k50hsgt71r400> (snip) _keepAlive; Restarting 10800s idle timeout
2019-11-06 19:19:01 INFO:IrcBridge Sending IRC message in (snip) as peremem[m] (connected=true)
2019-11-06 19:19:01 DEBUG:BridgedClient <peremem[m]@irc.ozinger.org#k50hsgt71r400> (snip) _keepAlive; Restarting 10800s idle timeout
2019-11-06 19:19:01 DEBUG:BridgedClient <peremem[m]@irc.ozinger.org#k50hsgt71r400> (snip) Joining channel (snip)
2019-11-06 19:19:01 INFO:IrcBridge [c71aao5e81s00] [I->M] SUCCESS  (4ms)
2019-11-06 19:19:03 DEBUG:BridgedClient <peremem[m]@irc.ozinger.org#k50hsgt71r400> (snip) Joined channel (snip)
Fatal TypeError: Cannot read property 'finally' of undefined
    at /home/psj/matrix-appservice-irc/node_modules/irc/lib/irc.js:1166:11
    at Array.map (<anonymous>)
    at Client._speak (/home/psj/matrix-appservice-irc/node_modules/irc/lib/irc.js:1164:36)
    at Client.say (/home/psj/matrix-appservice-irc/node_modules/irc/lib/irc.js:1140:17)
    at /home/psj/matrix-appservice-irc/lib/irc/BridgedClient.js:645:31
    at tryCatcher (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/psj/matrix-appservice-irc/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```

**Comment by Half-Shot** [comment]
Oh, I think I know what this is.

**Comment by Half-Shot** [comment]
https://github.com/matrix-org/matrix-appservice-irc/releases/tag/0.13.1

**Comment by Half-Shot** [comment]
Fixed in master.

**Comment by peremen** [comment]
Awesome, it works now. Thanks!

**Comment by darkblinded** [comment]
@Half-Shot Could you also release this version to npm?
