### ISSUE TITLE
gimpnet bridge failed to pick up room upgrade for #gnome:gnome.org

### ISSUE THREAD

**Issue by ara4n** [matrix-org/matrix-appservice-irc#982]
the upgrade failed to move the alias to the new room; meanwhile the bridge kept bridging the old room into place.

```
Feb 14 23:49:49 lethe gimpnetirc[594]: Feb-14 23:49:49.848 INFO RoomUpgradeHandler Got tombstone event for !TJpcuaFewUmutbvHqS:matrix.org -> !EzCPArJyrSebvklKjn:gnome.org
Feb 14 23:49:49 lethe gimpnetirc[594]: 2020-02-14 23:49:49 INFO:IrcBridge ::ffff:10.101.0.14 - - [14/Feb/2020:23:49:49 +0000] "PUT /transactions/4065225?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.9.1"
Feb 14 23:49:49 lethe gimpnetirc[594]: 2020-02-14 23:49:49 INFO:IrcBridge [-] POST https://gnome.modular.im/_matrix/client/r0/join/!EzCPArJyrSebvklKjn%3Agnome.org (AS) Body: "{}"
Feb 14 23:49:49 lethe gimpnetirc[594]: 2020-02-14 23:49:49 INFO:IrcBridge ::ffff:10.101.0.14 - - [14/Feb/2020:23:49:49 +0000] "PUT /transactions/4065226?access_token=<REDACTED> HTTP/1.1" 200 2 "-" "Synapse/1.9.1"
Feb 14 23:49:50 lethe gimpnetirc[594]: 2020-02-14 23:49:50 INFO:IrcBridge [gqhzwc87kb400] [M->I] SUCCESS  (16ms)
Feb 14 23:49:50 lethe gimpnetirc[594]: 2020-02-14 23:49:50 INFO:IrcBridge [-] POST https://gnome.modular.im/_matrix/client/r0/join/!EzCPArJyrSebvklKjn%3Agnome.org (AS) HTTP 200 "{\"room_id\": \"!EzCPArJyrSebvklKjn:gnome.org\"}"
Feb 14 23:49:50 lethe gimpnetirc[594]: Feb-14 23:49:50.053 DEBUG RoomUpgradeHandler Joined !EzCPArJyrSebvklKjn:gnome.org
Feb 14 23:49:50 lethe gimpnetirc[594]: Feb-14 23:49:50.055 ERROR RoomUpgradeHandler Couldn't handle room upgrade:  TypeError: Cannot read property 'getEntriesByMatrixId' of undefined
Feb 14 23:49:50 lethe gimpnetirc[594]:     at RoomUpgradeHandler._migrateStoreEntries (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/lib/components/room-upgrade-handler.js:110:41)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at RoomUpgradeHandler._onJoinedNewRoom (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/lib/components/room-upgrade-handler.js:74:40)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at /opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/lib/components/room-upgrade-handler.js:32:29
Feb 14 23:49:50 lethe gimpnetirc[594]:     at tryCatcher (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/util.js:26:23)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Promise._settlePromiseFromHandler (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:510:31)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Promise._settlePromiseAt (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:584:18)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Promise._settlePromises (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/promise.js:700:14)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Async._drainQueue (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:123:16)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Async._drainQueues (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:133:10)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at Immediate.Async.drainQueues (/opt/gimpnetirc/matrix-appservice-irc-0.15.2/node_modules/matrix-appservice-bridge/node_modules/bluebird/js/main/async.js:15:14)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at processImmediate (internal/timers.js:439:21)
Feb 14 23:49:50 lethe gimpnetirc[594]:     at process.topLevelDomainCallback (domain.js:130:23)
```

**Comment by ara4n** [comment]
I've bodged it for now with:

`update rooms set room_id='!EzCPArJyrSebvklKjn:gnome.org' where irc_channel='#gnome';`

on the gimpnet DB (yay for postgres!)

**Comment by ara4n** [comment]
...however, it would be good to know how to resync the membership of that room after bodging it like so. in the end i just restarted the whole bridge.

**Comment by Half-Shot** [comment]
#989 seemed to fix this.
